version: "3.1"

services:
  catalogodiscos:
    image: oliveiragustavo/catalogodiscos:3.0
    ports:
    - "8080:8080"

  catalogodiscosback:
    image: oliveiragustavo/catalogodiscos-back:3.0
    ports:
    - "8000:8000"
